version: '2'

services:

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5001:5000"
      - "9601:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"



